# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=1)),
                ('depart', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
